// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class DulceFacilDBContext : DbContext
{
    public DulceFacilDBContext()
    {
    }

    public DulceFacilDBContext(DbContextOptions<DulceFacilDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<DetallePedido> DetallePedido { get; set; }

    public virtual DbSet<Entrega> Entrega { get; set; }

    public virtual DbSet<Inventario> Inventario { get; set; }

    public virtual DbSet<Pedido> Pedido { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }

    public virtual DbSet<PuntoVenta> PuntoVenta { get; set; }

    public virtual DbSet<Repartidor> Repartidor { get; set; }

    public virtual DbSet<Ruta> Ruta { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(local);Initial Catalog=DulceFacilDB;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.id_cliente).HasName("PK__Cliente__677F38F5FC1C84E8");

            entity.Property(e => e.direccion).HasMaxLength(200);
            entity.Property(e => e.latitud).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.longitud).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.nombre).HasMaxLength(100);
            entity.Property(e => e.tipo).HasMaxLength(20);
            entity.Property(e => e.zona).HasMaxLength(100);
        });

        modelBuilder.Entity<DetallePedido>(entity =>
        {
            entity.HasKey(e => e.id_detalle).HasName("PK__DetalleP__4F1332DE95A79974");

            entity.Property(e => e.precio_unitario).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_pedidoNavigation).WithMany(p => p.DetallePedido)
                .HasForeignKey(d => d.id_pedido)
                .HasConstraintName("FK__DetallePe__id_pe__440B1D61");

            entity.HasOne(d => d.id_productoNavigation).WithMany(p => p.DetallePedido)
                .HasForeignKey(d => d.id_producto)
                .HasConstraintName("FK__DetallePe__id_pr__44FF419A");
        });

        modelBuilder.Entity<Entrega>(entity =>
        {
            entity.HasKey(e => e.id_entrega).HasName("PK__Entrega__017C2C8A50686A38");

            entity.Property(e => e.observaciones).HasMaxLength(200);

            entity.HasOne(d => d.id_pedidoNavigation).WithMany(p => p.Entrega)
                .HasForeignKey(d => d.id_pedido)
                .HasConstraintName("FK__Entrega__id_pedi__49C3F6B7");

            entity.HasOne(d => d.id_repartidorNavigation).WithMany(p => p.Entrega)
                .HasForeignKey(d => d.id_repartidor)
                .HasConstraintName("FK__Entrega__id_repa__4AB81AF0");
        });

        modelBuilder.Entity<Inventario>(entity =>
        {
            entity.HasKey(e => e.id_inventario).HasName("PK__Inventar__013AEB5164C15722");

            entity.HasOne(d => d.id_productoNavigation).WithMany(p => p.Inventario)
                .HasForeignKey(d => d.id_producto)
                .HasConstraintName("FK__Inventari__id_pr__3D5E1FD2");

            entity.HasOne(d => d.id_puntoNavigation).WithMany(p => p.Inventario)
                .HasForeignKey(d => d.id_punto)
                .HasConstraintName("FK__Inventari__id_pu__3E52440B");
        });

        modelBuilder.Entity<Pedido>(entity =>
        {
            entity.HasKey(e => e.id_pedido).HasName("PK__Pedido__6FF0148916F5F5D2");

            entity.Property(e => e.estado).HasMaxLength(20);

            entity.HasOne(d => d.id_clienteNavigation).WithMany(p => p.Pedido)
                .HasForeignKey(d => d.id_cliente)
                .HasConstraintName("FK__Pedido__id_clien__412EB0B6");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.id_producto).HasName("PK__Producto__FF341C0D9626223F");

            entity.Property(e => e.categoria).HasMaxLength(50);
            entity.Property(e => e.nombre).HasMaxLength(100);
            entity.Property(e => e.precio).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<PuntoVenta>(entity =>
        {
            entity.HasKey(e => e.id_punto).HasName("PK__PuntoVen__15EBCF0776FC6285");

            entity.Property(e => e.ciudad).HasMaxLength(100);
            entity.Property(e => e.direccion).HasMaxLength(200);
            entity.Property(e => e.nombre).HasMaxLength(100);
        });

        modelBuilder.Entity<Repartidor>(entity =>
        {
            entity.HasKey(e => e.id_repartidor).HasName("PK__Repartid__3D17037B6C063470");

            entity.Property(e => e.contacto).HasMaxLength(100);
            entity.Property(e => e.nombre).HasMaxLength(100);
        });

        modelBuilder.Entity<Ruta>(entity =>
        {
            entity.HasKey(e => e.id_ruta).HasName("PK__Ruta__33C9344F7CD82B25");

            entity.Property(e => e.distancia_km).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_repartidorNavigation).WithMany(p => p.Ruta)
                .HasForeignKey(d => d.id_repartidor)
                .HasConstraintName("FK__Ruta__id_reparti__4D94879B");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}