// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Entrega
{
    public int id_entrega { get; set; }

    public int? id_pedido { get; set; }

    public int? id_repartidor { get; set; }

    public DateOnly? fecha_entrega { get; set; }

    public string observaciones { get; set; }

    public virtual Pedido id_pedidoNavigation { get; set; }

    public virtual Repartidor id_repartidorNavigation { get; set; }
}