// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Inventario
{
    public int id_inventario { get; set; }

    public int? id_producto { get; set; }

    public int? id_punto { get; set; }

    public int? cantidad { get; set; }

    public virtual Producto id_productoNavigation { get; set; }

    public virtual PuntoVenta id_puntoNavigation { get; set; }
}