// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Pedido
{
    public int id_pedido { get; set; }

    public int? id_cliente { get; set; }

    public DateOnly? fecha { get; set; }

    public string estado { get; set; }

    public virtual ICollection<DetallePedido> DetallePedido { get; set; } = new List<DetallePedido>();

    public virtual ICollection<Entrega> Entrega { get; set; } = new List<Entrega>();

    public virtual Cliente id_clienteNavigation { get; set; }
}