// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Producto
{
    public int id_producto { get; set; }

    public string nombre { get; set; }

    public string categoria { get; set; }

    public decimal? precio { get; set; }

    public virtual ICollection<DetallePedido> DetallePedido { get; set; } = new List<DetallePedido>();

    public virtual ICollection<Inventario> Inventario { get; set; } = new List<Inventario>();
}