// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class PuntoVenta
{
    public int id_punto { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public string ciudad { get; set; }

    public virtual ICollection<Inventario> Inventario { get; set; } = new List<Inventario>();
}