// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Repartidor
{
    public int id_repartidor { get; set; }

    public string nombre { get; set; }

    public string contacto { get; set; }

    public virtual ICollection<Entrega> Entrega { get; set; } = new List<Entrega>();

    public virtual ICollection<Ruta> Ruta { get; set; } = new List<Ruta>();
}