// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Ruta
{
    public int id_ruta { get; set; }

    public int? id_repartidor { get; set; }

    public DateOnly? fecha { get; set; }

    public decimal? distancia_km { get; set; }

    public TimeOnly? tiempo_estimado { get; set; }

    public virtual Repartidor id_repartidorNavigation { get; set; }
}